import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Relogio from "@/componentes/Relogio/Relogio"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = new Date()
  return (
    <html lang="en">
      <body className='flex flex-col justify-start gap-4 p-20 items-center min-h-screen'>
        
        <header className="flex flex-col items-center">
          <h1>React & Next.js</h1>
          <nav className="flex gap-4">
            <Link href="/" className="hover:underline">Intro</Link>
            <Link href="/sobre" className="hover:underline">Sobre</Link>
            <Link href="/caracteristicas" className="hover:underline">Caracteristicas </Link>
            <Link href="/tecnologias" className="hover:underline">Tecnologias</Link>
            <Link href="/projetos" className="hover:underline">Projetos</Link>
            <Link href="/contador" className="hover:underline">Contador</Link>
            <Link href="/input" className="hover:underline">Input</Link>
            <Link href="/deisiShop" className="hover:underline">DEISIshop</Link>


            <Link href="/municipalities" className="hover:underline">Municipios</Link>

          </nav>
        </header>
        
        <main className="bg-blue-200 p-5 rounded-2xl w-[600px] max-w-2xl min-h-[70vh]">
          {children}
        </main>
        
        <footer>{data.getFullYear()}
          <br></br>
          <Relogio />
        </footer>

      </body>
    </html>
  );
}
